// app/prototypes/undercity-monitor/lib/mockState.ts

import type { SessionState } from './types';

export const MOCK_SESSIONS: SessionState[] = [
  {
    sessionId: 'session-1',
    sessionName: 'MSS Integration',
    timestamp: new Date().toISOString(),
    agents: [
      {
        id: 'thrall',
        name: 'Thrall',
        wowName: 'Thrall',
        title: 'War Chief',
        role: 'project-lead',
        rolePuck: 'tank',
        state: 'briefing',
        zone: 'guildHall',
        activity: 'Reviewing the pull',
        contextHealth: 0.85,
        isCompacting: false,
        waitingForInput: false,
        currentTool: null,
      },
      {
        id: 'garrosh',
        name: 'Garrosh Hellscream',
        wowName: 'Garrosh',
        title: 'Overlord',
        role: 'ops-coordinator',
        rolePuck: 'dps',
        state: 'working',
        zone: 'forge',
        activity: 'Forging ticket: SIPR Cert Handoff',
        contextHealth: 0.45,
        isCompacting: false,
        waitingForInput: false,
        currentTool: 'mcp__linear__save_issue',
      },
      {
        id: 'cho',
        name: 'Lorewalker Cho',
        wowName: 'Cho',
        title: 'Lorekeeper',
        role: 'technical-writer',
        rolePuck: 'healer',
        state: 'working',
        zone: 'scriptorium',
        activity: 'Inscribing page: Weekly Status',
        contextHealth: 0.9,
        isCompacting: false,
        waitingForInput: false,
        currentTool: 'mcp__notion__notion-create-pages',
      },
      {
        id: 'faranell',
        name: 'Faranell',
        wowName: 'Faranell',
        title: 'Royal Apothecary',
        role: 'mcp-integrator',
        rolePuck: 'crafter',
        state: 'compacting',
        zone: 'apothecary',
        activity: 'Drinking potion...',
        contextHealth: 0.18,
        isCompacting: true,
        waitingForInput: false,
        currentTool: null,
      },
      {
        id: 'alexstrasza',
        name: 'Alexstrasza',
        wowName: 'Alexstrasza',
        title: 'Life-Binder',
        role: 'ux-design-engineer',
        rolePuck: 'healer',
        state: 'waiting',
        zone: 'summonStone',
        activity: 'Waiting for summon...',
        contextHealth: 0.55,
        isCompacting: false,
        waitingForInput: true,
        currentTool: null,
      },
      {
        id: 'sylvanas',
        name: 'Lady Sylvanas',
        wowName: 'Sylvanas',
        title: 'Dark Ranger',
        role: 'frontend-engineer',
        rolePuck: 'dps',
        state: 'waiting',
        zone: 'summonStone',
        activity: 'LFG...',
        contextHealth: 0.8,
        isCompacting: false,
        waitingForInput: true,
        currentTool: null,
      },
      {
        id: 'lorthemar',
        name: "Lor'themar Theron",
        wowName: "Lor'themar",
        title: 'Regent Lord',
        role: 'product-manager',
        rolePuck: 'strategist',
        state: 'briefing',
        zone: 'guildHall',
        activity: 'Assigning roles',
        contextHealth: 0.72,
        isCompacting: false,
        waitingForInput: false,
        currentTool: null,
      },
    ],
    quests: [
      {
        id: 'q1',
        title: 'Forge Linear Tickets: MSS Integration',
        objectives: [
          { text: 'Forge blocker: SIPR Cert Handoff', complete: true },
          { text: 'Forge blocker: NPE Cert Renewal', complete: true },
          { text: 'Temper milestone: MSS Staging Deploy', complete: false },
        ],
        assignedAgent: 'Garrosh Hellscream',
        progress: 2,
        maxProgress: 3,
        complete: false,
      },
      {
        id: 'q2',
        title: 'Inscribe Weekly Status Update',
        objectives: [
          { text: 'Transcribe lore for the leadership council', complete: true },
        ],
        assignedAgent: 'Lorewalker Cho',
        progress: 1,
        maxProgress: 1,
        complete: true,
      },
      {
        id: 'q3',
        title: 'Brew Figma Transmutation: Dashboard',
        objectives: [
          { text: 'Distill filter panel components', complete: false },
          { text: 'Transmute layout from design realm', complete: false },
          { text: 'Decant design tokens into code', complete: false },
          { text: 'Bottle final mockup for review', complete: false },
        ],
        assignedAgent: 'Faranell',
        progress: 0,
        maxProgress: 4,
        complete: false,
      },
      {
        id: 'q4',
        title: 'Defend the Raid: NGC2 Demo Prep',
        objectives: [
          { text: 'Rally warband for Thursday encounter', complete: true },
          { text: 'Verify integration test armor', complete: false },
          { text: 'Scout battlefield with Sarah', complete: false },
          { text: 'Rehearse the pull', complete: false },
          { text: 'Final ready check', complete: false },
        ],
        assignedAgent: 'Thrall',
        progress: 1,
        maxProgress: 5,
        complete: false,
      },
      {
        id: 'q5',
        title: 'Scout the Battlefield: Filter Panel',
        objectives: [
          { text: 'Awaiting orders — left rail or top bar?', complete: false },
        ],
        assignedAgent: 'Alexstrasza',
        progress: 0,
        maxProgress: 1,
        complete: false,
      },
    ],
    raidBriefing: {
      active: true,
      topic: 'MSS Integration Sprint Planning',
      participants: ['Thrall', "Lor'themar"],
    },
  },
  {
    sessionId: 'session-2',
    sessionName: 'Undercity Build',
    timestamp: new Date().toISOString(),
    agents: [],
    quests: [],
    raidBriefing: { active: false, topic: null, participants: [] },
  },
  {
    sessionId: 'session-3',
    sessionName: 'NGC2 Demo Prep',
    timestamp: new Date().toISOString(),
    agents: [],
    quests: [],
    raidBriefing: { active: false, topic: null, participants: [] },
  },
];
